relanz/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('community/', include('community.urls')),
    path('challenge/', include('challenge.urls')),
    path('', include('django.contrib.auth.urls')),
    # path('', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

relanz/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
    path('ranking/', views.ranking, name="ranking"),
]

relanz/user/urls.py
from django.urls import path
from . import views
from .views import CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
    path('user_delete/', views.user_delete, name="user_delete"),
    path('api/identify', views.identify, name="identify"),
    path('userinfo/', views.userinfo, name="userinfo"), #계정 마이페이지
    path('content/', views.content, name="content"), #닉네임, 나이, 성별 받아오기 - 하나의 페이지로 통합
    path('moreInfo/', views.moreInfo, name="moreInfo"), # 하단바 더보기 페이지

    
    path('survey/', views.survey, name="survey"), # 해소 정도 -> 닉네임, 나이, 성별 작성 후 가정 먼저 설문조사하는 페이지 (figma 참고)
    path('tagsurvey/', views.tagsurvey, name="tagsurvey"), # 유저의 tag 선택
    path('avatar/', views.avatar, name="avatar"), # 프로필 이미지
    path('findid/', views.findid, name="findid"), # 아이디 찾기

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('email_sent/', views.email_sent, name="email_sent"), # 이메일 전송
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"), # 이메일 인증 활성화
]

relanz/main/views/home_views.py
from django.shortcuts import render, redirect
from user.models import User, UserTag
from challenge.models import Challenge, ChallengeTag, Participant
from community.models import Article
from django.forms.models import model_to_dict
from django.db.models import Q
import random
from collections import Counter
from datetime import datetime
from django.db.models import Sum, Count


# Create your views here.
def home(request):
    user=request.user
    if user.is_authenticated:
        if not user.is_email_valid:
            return redirect('user:email_sent')
        elif not user.nickname:
            return render(request, 'main/home.html', {'user':user}) 
        participant = Participant.objects.filter(user=user.id)
        try:
            if not participant.exists():
                user_tag = UserTag.objects.get(user=user.id)
                basic_tags_ = {
                '아침': user_tag.morning,
                '점심': user_tag.afternoon,
                '저녁': user_tag.evening,
                '실내': user_tag.inside,
                '야외': user_tag.outside,
                '혼자': user_tag.solo,
                '여럿이': user_tag.group,
                '정적인': user_tag.static,
                '동적인': user_tag.dynamic,
                }
                tag_lists_=[]
                for tag_name, tag_value in basic_tags_.items():
                    if tag_value is True:
                        tag_lists_.append(tag_name)
                basic_tags = {
                'morning': user_tag.morning,
                'afternoon': user_tag.afternoon,
                'evening': user_tag.evening,
                'inside': user_tag.inside,
                'outside': user_tag.outside,
                'solo': user_tag.solo,
                'group': user_tag.group,
                'pay': user_tag.pay,
                'free': user_tag.free,
                'static': user_tag.static,
                'dynamic': user_tag.dynamic,
                }

                tag_lists=[]
                for tag_name, tag_value in basic_tags.items():
                    if tag_value is True:
                        tag_lists.append(tag_name)

                challenge_query = Q()
                for tag_list in tag_lists:
                    challenge_query |= Q(**{tag_list: True})
                challenges_tags = ChallengeTag.objects.filter(challenge_query)

                participants=[]
                for challenge_tag in challenges_tags:
                # 참여자 모델 관련 처리(참여자 쿼리 가져오기, 쿼리 순서 정렬, 정렬된 순서를 바탕으로 쿼리셋 생성)
                    participants.append(Participant.objects.filter(challenge_id=challenge_tag.challenge.id))
                
                sorted_participants = []
                for participant in participants:
                    if participant:
                        sorted_participants.append(participant.values('challenge_id').annotate(count=Count('user_id')).order_by('-count').distinct())
                    else:
                        sorted_participants.append(int(0))
                i = 0
                for sorted_participant in sorted_participants:
                    if sorted_participant != 0:
                        sorted_participants[i] = sorted_participant[0]['count']
                    i+=1
                combined_data = list(zip(challenges_tags, sorted_participants))
                res_data = survey_result(request)
                res_data2 = {'user':user, 'tag_lists':tag_lists_, 'combined_data':combined_data}
                res_data.update(res_data2)

                return render(request, 'main/home.html', res_data)
            

            else:
                user_tag = UserTag.objects.get(user=user.id)
                basic_tags_ = {
                '아침': user_tag.morning,
                '점심': user_tag.afternoon,
                '저녁': user_tag.evening,
                '실내': user_tag.inside,
                '야외': user_tag.outside,
                '혼자': user_tag.solo,
                '여럿이': user_tag.group,
                '정적인': user_tag.static,
                '동적인': user_tag.dynamic,
                }
                tag_lists_=[]
                for tag_name, tag_value in basic_tags_.items():
                    if tag_value is True:
                        tag_lists_.append(tag_name)

                basic_tags = {
                'morning': user_tag.morning,
                'afternoon': user_tag.afternoon,
                'evening': user_tag.evening,
                'inside': user_tag.inside,
                'outside': user_tag.outside,
                'solo': user_tag.solo,
                'group': user_tag.group,
                'pay': user_tag.pay,
                'free': user_tag.free,
                'static': user_tag.static,
                'dynamic': user_tag.dynamic,
                }

                tag_lists=[]
                for tag_name, tag_value in basic_tags.items():
                    if tag_value is True:
                        tag_lists.append(tag_name)
                challenges = ChallengeTag.objects.filter(**{tag_list: True for tag_list in tag_lists})

                # id, user_id 등 불필요한 데이터 제외
                minus_tag = ['id','user']
                for tag_name, tag_value in basic_tags.items():
                    minus_tag.append(tag_name)
                
                # 유저가 릴렌지를 참여함에 따라 빈도 수가 높은 릴렌지 태그를 뽑음
                user_tag_dict = model_to_dict(user_tag)
                for i in range(0, len(minus_tag)):
                    del user_tag_dict[f'{minus_tag[i]}']
                sorted_user_tag = sorted(user_tag_dict.items(), key=lambda x:x[1], reverse=True)
                sorted_user_keys = [item[0] for item in sorted_user_tag]

                # 기본 태그를 통해 가져온 챌린지와 릴렌지 태그를 통해 가져온 챌린지 쿼리를 합집합
                basic_tag_query =Q()
                for key in sorted_user_keys[:4]:
                    basic_tag_query |=Q(**{key: True})
                challenge_tag_query=Q()
                for key in tag_lists:
                    challenge_tag_query |=Q(**{key: True})
                challenge_query = basic_tag_query|challenge_tag_query
                
                challenge_tags = ChallengeTag.objects.filter(challenge_query).order_by(f'-{sorted_user_keys[0]}', f'-{sorted_user_keys[1]}', f'-{sorted_user_keys[2]}', f'-{sorted_user_keys[3]}')
                # 이미 참여한 챌린지는 추천에서 제외
                minus_challenge = []
                # 정렬된 챌린지의 아이디를 뽑아서, requset.user와 challenge.id를 통해 파싱
                for challenge_tag in challenge_tags:
                    already_participant=Participant.objects.filter(challenge=challenge_tag.challenge, user=user.id)
                    # 빈쿼리셋이 반환된 게 아니라면, 이미 참여하고 있는 챌린지 (TRUE)
                    if already_participant.exists():  
                        minus_challenge.append(challenge_tag)
                # x가 sorted_challenge의 element면서 참여하고 있는 챌린지가 아닐 때
                challenge_tags = [x for x in challenge_tags if x not in minus_challenge]

                participants=[]
                for challenge_tag in challenge_tags:
                # 참여자 모델 관련 처리(참여자 쿼리 가져오기, 쿼리 순서 정렬, 정렬된 순서를 바탕으로 쿼리셋 생성)
                    participants.append(Participant.objects.filter(challenge_id=challenge_tag.challenge.id))
                
                sorted_participants = []
                for participant in participants:
                    if participant:
                        sorted_participants.append(participant.values('challenge_id').annotate(count=Count('user_id')).order_by('-count').distinct())
                    else:
                        sorted_participants.append(int(0))
                i = 0
                for sorted_participant in sorted_participants:
                    if sorted_participant != 0:
                        sorted_participants[i] = sorted_participant[0]['count']
                    i+=1

                combined_data = list(zip(challenge_tags, sorted_participants))

                # report 분석 알고리즘
                participant_report = {
                'morning': 0,
                'afternoon': 0,
                'evening': 0,
                'inside': 0,
                'outside': 0,
                'solo': 0,
                'group': 0,
                'pay': 0,
                'free': 0,
                'static': 0,
                'dynamic': 0,
                }
                
                # user_id를 통해 참여자 모델 가져오기
                user_participants = Participant.objects.filter(user=user.id)
                for user_participant in user_participants:
                    analysis_challenge = ChallengeTag.objects.get(challenge=user_participant.challenge_id)
                    for key in participant_report.keys():
                        if getattr(analysis_challenge, key):
                            participant_report[key] += 1

                analysis_user_tag = [k for k, v in sorted(participant_report.items(), key=lambda item: item[1], reverse=True)]
                # 내가 최근 남긴 인증 10개 중에 인증을 가장 많이 남긴 릴렌지 출력
                articles = Article.objects.filter(author__user=user)
                articles = articles.order_by('-created_at')
                if len(articles) > 10:
                    articles=articles[:10]
                like_challenge_list=[]
                for article in articles:
                    like_challenge = article.challenge_id
                    like_challenge_list.append(like_challenge)

                if not like_challenge_list:
                    if len(minus_challenge) == 1:
                        r = 0
                    else:
                        r = random.randint(0, len(minus_challenge)-1)
                    most_like_challenge=minus_challenge[r]
                else:
                    challenge_element = Counter(like_challenge_list)
                    most_common_challenge = challenge_element.most_common(1)[0][0]
                    most_like_challenge = Challenge.objects.get(id=most_common_challenge)

relanz/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>
      {% block title %}{% endblock title %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static "css/base.css"%}">
    <link rel="shortcut icon" href="{% static "icons/favicon.png" %}" type="image/x-icon">
    {% block extrahead %}{% endblock extrahead %}
  </head>

  <body>
    <div id="pc-content">
      <div id="side-box">
        <div class="logo-box">
          <img src="{% static "logo/relanz-logo1.png" %}" alt="relanz-logo1">
        </div>
        <div class="message-box">
          <div class="large-message">
            <p>올바른 스트레스 해소법,<br/>릴렌즈와 함께 찾아봐!</p>
          </div>
          <div class="small-message">
            <p>챌린지 말고, 이젠 릴렌지 하자!</p>
          </div>
        </div>
        <div class="word-box">
          <div class="word-define">
            <span>Relax+Challenge=릴렌지</span>
          </div>
          <div class="word-describe">
            <p>
              나한테 맞는 스트레스 해소법 찾고,<br/>릴렌즈와 함께 관리를 시작해보세요
            </p>
          </div>
        </div>
      </div>
    </div>
    <div id="mobile-content">
      {% block content %}{% endblock content %}
    </div>
    {% block scripts%}{% endblock scripts%}
  </body>

</html>

relanz/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Home
{% endblock title %}

{% block extrahead %}
{% comment %} <link rel="stylesheet" type="text/css" href="{% static "css/home.css"%}"> {% endcomment %}
{% endblock extrahead %}

{% block content%}
    {% if user.is_authenticated %}
        <a href="{% url 'user:signout' %}">로그아웃</a>
        <h1>환영합니다! {{user.username}} 님</h1>
    {% else %}
        <a href="{% url 'user:signup' %}">회원가입</a>
        <a href="{% url 'user:signin' %}">로그인</a>
    {% endif %}
{% endblock  %}

relanz/templates/mobileBase.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {% block mobile_title %}{% endblock mobile_title %}
{% endblock title %}

{% block extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/mobileBase.css"%}">
  {% block mobile_extrahead %}{% endblock mobile_extrahead %}
{% endblock extrahead %}

{% block content%}
  <div class="mobile-header">
    <a href="{% url 'main:home' %}">
      <img src="{% static "logo/relanz-logo1.png" %}" alt="relanz-logo1">
    </a>
  </div>
  <div class="mobile-content">
    {% block mobile_content %}{% endblock mobile_content %}
  </div>
  <div class="mobile-nav">
    <ul class="menu-list">
      <li>
        <a class="home" href="{% url 'main:home' %}">
          <img src="{% static "icons/Home_icon.png"%}" alt="home-icon">
        </a>
      </li>
      <li>
        <a class="my" href="{% url 'user:userinfo' %}">
          <img src="{% static "icons/My_icon.png"%}" alt="around-icon">
        </a>
      </li>
      <li>
        <a class="ranking" href="{% url 'main:ranking' %}">
          <img src="{% static "icons/Ranking_icon.png"%}" alt="community-icon">
        </a>
      </li>
      <li>
        <a class="more" href="{% url 'user:moreInfo' %}">
          <img src="{% static "icons/More_icon.png"%}" alt="settings-icon">
        </a>
      </li>
    </ul>
  </div>
{% endblock %}

{% block scripts%}
  <script>
    {% if not user.nickname %}
      const mobileHeader = document.querySelector('.mobile-header');
      const mobileNav = document.querySelector('.mobile-nav');
      mobileHeader.style.display = 'none';
      mobileNav.style.display = 'none';
    {% endif %}
  </script>
  {% block mobile-scripts %}
  {% endblock %}
{% endblock %}