relanz/community/urls.py
from django.urls import path
from .views import new, detail, edit, delete, communityHome, like
from .views import new, detail, edit, delete, communityHome, like, myArticles

app_name = 'community'

urlpatterns = [
    path('communityHome/<int:challenge_id>', communityHome, name='communityHome'),
    path('<int:challenge_id>/<int:article_id>', detail, name='detail'),
    path('<int:challenge_id>/new', new, name='new'),
    path('edit/<int:challenge_id>/<int:article_id>', edit, name='edit'),
    path('delete/<int:challenge_id>/<int:article_id>', delete, name='delete'),
    path('<int:article_id>/like/', like, name='like'),
    path('communityHome/<int:challenge_id>/myArticles', myArticles, name='myArticles')
]

relanz/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('community/', include('community.urls')),
    path('challenge/', include('challenge.urls')),
    path('', include('django.contrib.auth.urls')),
    # path('', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

relanz/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
    path('ranking/', views.ranking, name="ranking"),
]

relanz/user/urls.py
from django.urls import path
from . import views
from .views import CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView

app_name = 'user'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
    path('user_delete/', views.user_delete, name="user_delete"),
    path('api/identify', views.identify, name="identify"),
    path('userinfo/', views.userinfo, name="userinfo"), #계정 마이페이지
    path('content/', views.content, name="content"), #닉네임, 나이, 성별 받아오기 - 하나의 페이지로 통합
    path('moreInfo/', views.moreInfo, name="moreInfo"), # 하단바 더보기 페이지

    
    path('survey/', views.survey, name="survey"), # 해소 정도 -> 닉네임, 나이, 성별 작성 후 가정 먼저 설문조사하는 페이지 (figma 참고)
    path('tagsurvey/', views.tagsurvey, name="tagsurvey"), # 유저의 tag 선택
    path('avatar/', views.avatar, name="avatar"), # 프로필 이미지
    path('findid/', views.findid, name="findid"), # 아이디 찾기

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('email_sent/', views.email_sent, name="email_sent"), # 이메일 전송
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"), # 이메일 인증 활성화
]

relanz/user/views/find_views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from ..models import User
from django.core.mail import send_mail
import os
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.views.decorators.csrf import csrf_exempt

from django.utils.decorators import method_decorator

@csrf_exempt
def findid(request):
    if request.method == 'POST':
        email = request.POST['email']
        try:
            user = User.objects.get(email=email)
            subject = f'회원님의 아이디는 {user.username}입니다.'
            message = f"회원님의 아이디는 {user.username}입니다. 이 메일은 회신불가입니다."
            from_email = os.environ.get('EMAIL_HOST_USER')
            recipient_list = [email]

            send_mail(subject=subject, message=message, from_email=from_email, recipient_list=recipient_list)
            
            res_data = {'success': '입력하신 이메일로 아이디가 전송되었습니다'}

            return render(request, 'user/findid.html', res_data)
        
        # 일치하는 이메일 없으면 에러메시지 반환
        except User.DoesNotExist:

            res_data = {'error': '일치하는 사용자가 없습니다. 이메일을 다시 입력해주세요.'}
            
            return render(request, 'user/findid.html', res_data)

    return render(request, 'user/findid.html')


# 비밀번호 재설정 커스터마이징을 위한 상속
class CustomPasswordResetView(PasswordResetView):
    template_name = 'user/pw_reset.html'
    email_template_name = 'user/pw_reset_email.html'
    subject_template_name = 'user/pw_reset_subject.txt'
    success_url = reverse_lazy("user:password_reset_done")

class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = "user/pw_reset_done.html"

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "user/pw_reset_confirm.html"
    success_url = reverse_lazy("user:password_reset_complete")

class CustomPasswordResetCompleteView(PasswordResetCompleteView):

    template_name = "user/pw_reset_complete.html"

relanz/user/views/profile_views.py
from django.http import HttpResponseForbidden, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from config.email_decorator import email_verified_required
from user.models import User, UserTag
from challenge.models import Challenge, Participant,ChallengeTag
from django.views.decorators.csrf import csrf_exempt



@csrf_exempt
@login_required(login_url='/user/signin')
@email_verified_required
def content(request):
    if request.method=="GET":
        user = User.objects.get(id=request.user.id)
        return render(request, 'user/content.html', {'user':user})
    if request.method=="POST":
        message = {}
        user = request.user
        user = User.objects.get(username=user.username)
        nickname = request.POST.get('nickname')
        birth = request.POST.get('birth')
        sex = request.POST.get('sex')
        if not nickname:
            message['error'] = "닉네임을 입력해주세요."
            return render(request, 'user/content.html', message)
        elif user.nickname is not None or user.nickname == nickname:
            user.nickname = nickname
            user.birth = birth
            user.sex = sex
            user.save()
            return redirect('user:userinfo')
        else:
            if User.objects.filter(nickname=nickname).exists():
                message['error'] = "이미 존재하는 닉네임입니다."
                return render(request, 'user/content.html', message)
            user.nickname = nickname
            user.birth = birth
            user.sex = sex
            user.save()
            return redirect('user:survey')
        

@csrf_exempt
@login_required(login_url='/user/signin')
@email_verified_required
def avatar(request):
    if request.method == 'GET':
        user = User.objects.get(id=request.user.id)
        return render(request, 'user/avatar.html')
    if request.method == 'POST':
        user = request.user
        if user.avatar is None:
            user.avatar = request.POST.get('avatar')
            user.save()
            return redirect('main:home')
        user.avatar = request.POST.get('avatar')
        user.save()
        return redirect('user:userinfo')



@login_required(login_url='/user/signin')
def userinfo(request):
    user = request.user
    user = User.objects.get(username=user.username) 
    user_tag = UserTag.objects.get(user=user.id)
    basic_tags_ = {
        '아침': user_tag.morning,
        '점심': user_tag.afternoon,
        '저녁': user_tag.evening,
        '실내': user_tag.inside,
        '야외': user_tag.outside,
        '혼자': user_tag.solo,
        '여럿이': user_tag.group,
        '정적인': user_tag.static,
        '동적인': user_tag.dynamic,
        }
    tag_lists_=[]
    for tag_name, tag_value in basic_tags_.items():
        if tag_value is True:
            tag_lists_.append(tag_name)
    
    
    participants = Participant.objects.filter(user=user.id)
    challenges=[]
    
    for participant in participants:
        challenge_tag = ChallengeTag.objects.get(challenge=participant.challenge)
        basic_tags = {
            '아침': challenge_tag.morning,
            '점심': challenge_tag.afternoon,
            '저녁': challenge_tag.evening,
            '실내': challenge_tag.inside,
            '야외': challenge_tag.outside,
            '혼자': challenge_tag.solo,
            '여럿이': challenge_tag.group,
            '정적인': challenge_tag.static,
            '동적인': challenge_tag.dynamic,
            '유료' : challenge_tag.pay,
            '무료' : challenge_tag.free
        }
        challenge_tag_list=[]
        for tag_name, tag_value in basic_tags.items():
            if tag_value == True:
                challenge_tag_list.append(tag_name)
        challenges.append((participant.challenge, challenge_tag_list))
    res_data = {'user':user, 'tags':tag_lists_, 'challenges':challenges}
    
    return render(request, 'user/userinfo.html', res_data)

    
    

relanz/user/views/tag_views.py
from django.shortcuts import render, redirect, get_object_or_404
from ..models import User, UserTag
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from config.email_decorator import email_verified_required
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
@login_required(login_url='/user/signin')
@email_verified_required
def survey(request):
    if request.method=="GET":
        user = request.user
        return render(request, 'tag/survey.html', {"user":user.nickname})
    if request.method=="POST":
        user=request.user
        if user.nickname is None:
            return redirect('user:content')
        if user.is_authenticated:
            user.survey_result_count = int(request.POST.get('survey_result_count'))
            user.save()
        return redirect('user:tagsurvey')
    return render(request, 'main/home.html')

@csrf_exempt
@login_required(login_url='/user/signin')
@email_verified_required
def tagsurvey(request):
    user=request.user
    if request.method=="GET":
        try:
            tags = UserTag.objects.get(user=user)
        except UserTag.DoesNotExist:
            tags = UserTag.objects.create(user=user)
        return render(request, 'tag/tagsurvey.html', {'tags':tags})
    if request.method=="POST":
        if user.nickname is None:
            return redirect('user:content')
        tags = UserTag.objects.get(user=user)
        morning = request.POST.get('morning')
        afternoon = request.POST.get('afternoon')
        evening = request.POST.get('evening')
        inside = request.POST.get('inside')
        outside = request.POST.get('outside')
        solo = request.POST.get('solo')
        group = request.POST.get('group')
        static = request.POST.get('static')
        dynamic = request.POST.get('dynamic')
        anytime = request.POST.get('anytime')
        tag_cnt = 0
        tag_lists = [morning, afternoon, evening, inside, outside, solo, group, static, dynamic, anytime]
        for tag_list in tag_lists:
            if tag_list is not None:
                tag_cnt += 1
        if tag_cnt > 0:
            if morning == 'morning':
                tags.morning = True
            else:
                tags.morning =False

            if afternoon == 'afternoon':
                tags.afternoon = True
            else:
                tags.afternoon =False

            if evening == 'evening':
                tags.evening = True
            else:
                tags.evening =False

            if inside == 'inside':
                tags.inside = True
            else:
                tags.inside =False

            if outside == 'outside':
                tags.outside = True
            else:
                tags.outside =False

            if solo == 'solo':
                tags.solo = True
            else:
                tags.solo =False

            if group == 'group':
                tags.group = True
            else:
                tags.group =False

            if static == 'static':
                tags.static = True
            else:
                tags.static =False

            if dynamic == 'dynamic':
                tags.dynamic = True
            else:
                tags.dynamic =False

            if anytime == 'anytime':
                tags.morning = True
                tags.afternoon = True
                tags.evening = True
            tags.save()
            if user.avatar is None:
                return redirect('user:avatar')
            else:
                return redirect('user:userinfo')
        else:
            messages.add_message(request, messages.ERROR, '')
            return render(request, 'tag/tagsurvey.html')
    return render(request, 'main/home.html', {user:user})

relanz/templates/user/accountInfo.html
<h1>유저 정보</h1>
<br />
<hr />
<h2>{{user.username}}</h2>
<hr />
{{user.nickname}}
<hr />
<p>닉네임: {{user.nickname}}</p>

<p>나이: {{ user.birth }}</p>
{% if user.sex == 'male' %}
<p>성별: 남성 </p>
{% else %}
<p>성별: 여성 </p>
{% endif %}

<a href="{% url 'main:home' %}">홈으로</a>

relanz/templates/user/activation_email.html
{{user.username}}님, 아래 링크를 클릭하여 계정을 활성화하세요:
http://{{domain}}{% url 'user:activate' uid token %}

relanz/templates/user/email_sent.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  이메일 인증을 완료하세요!
{% endblock title %}

{% block extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/user/email_sent.css"%}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock extrahead %}


{% block content%}
  <div id="email_validation">
    <p class="signin-complete">이메일을 인증하면<br>회원가입 완료!</p>
    <div class="welcome-box">
      <img src="{% static "images/welcome-box.png" %}" alt="welcome-img">
    </div>
    <p class="info-message">인증 메일 보내기 버튼을 눌러<br>메일함에 도착한 링크를 통해<br>회원가입을 완료해 주세요</p>
    <div class="user-button" id="send_email">인증 메일 보내기</div>
    <div class="user-button" id="complete_verification">인증 완료</div>
    
    <div id="alert">
      <div class="popup">
        <div class="close-button"><img src="{% static "icons/close.png"%}" alt="x"></div>
        <img src="{% static "icons/alert.png"%}" alt="alert">
        <span>이메일 인증을 완료해주세요</span>
      </div>
    </div>
  </div>
  <div class="loading-cover"><div class="loading-image-div"><img src="{% static 'icons/loading.png'%}" alt="loading"></div></div>
  <a class="logout" href="{% url 'user:signout' %}">로그아웃</a>
{% endblock %}

{% block scripts %}

  <script>
    const sendEmailButton = document.getElementById("send_email");
    const completeVerificationButton = document.getElementById("complete_verification");
    const popupAlert = document.getElementById('alert');
    const closeButton = document.querySelector('#alert > .popup > .close-button');
    const loadingCover = document.querySelector('.loading-cover')
    
    function completeVerify() {
      $.ajax({
        type: "POST",
        headers: {
          'X-CSRFToken': '{{ csrf_token }}',
        },
        url: "/user/email_sent/",  // 이메일 보내기 요청을 처리하는 URL
        data: {
          complete_verification: true  // send_email 파라미터를 설정하여 서버에서 이메일 보내기 동작을 수행
        },
        success: function(response) {
          // 성공적인 응답을 받은 경우
          console.log(response.message);
          window.location.href = "{% url 'main:home' %}";
        },
        error: function(xhr, status, error) {
          // 오류 응답을 받은 경우
          console.error(error);  // 오류 메세지 출력
          popupAlert.style.display = 'block';
        }
      });
    }

    function sendEmail() {
      // 로딩표시 보이기
      loadingCover.style.display = 'block';
      // AJAX 요청 보내기
      $.ajax({
        type: "POST",
        headers: {
          'X-CSRFToken': '{{ csrf_token }}',
        },
        url: "/user/email_sent/",  // 이메일 보내기 요청을 처리하는 URL
        data: {
          send_email: true  // send_email 파라미터를 설정하여 서버에서 이메일 보내기 동작을 수행
        },
        success: function(response) {
          // 성공적인 응답을 받은 경우
          console.log(response.message);  // 응답 메세지 출력
          // 추가로 처리할 작업 수행
          sendEmailButton.style.backgroundColor = '#fff';
          sendEmailButton.style.color = '#71a1ff';
          sendEmailButton.style.border = '2px solid #71a1ff';
          sendEmailButton.innerText = "인증 메일 다시 보내기";

          completeVerificationButton.style.cursor = 'pointer';
          completeVerificationButton.style.backgroundColor = '#71a1ff';
          completeVerificationButton.classList.add('active');

          completeVerificationButton.addEventListener("click", completeVerify);
          loadingCover.style.display = 'none';
        },
        error: function(xhr, status, error) {
          // 오류 응답을 받은 경우
          console.error(error);  // 오류 메세지 출력
          loadingCover.style.display = 'none';
        }
      });
    }

    sendEmailButton.addEventListener("click", sendEmail);
    closeButton.addEventListener("click", ()=> {
      popupAlert.style.display = 'none';
    });

      
  </script>
{% endblock %}

relanz/templates/user/findid.html
{% extends 'mobileBase.html' %}
{% load static %}
{% block title %}
  findId
{% endblock title %}
{% block extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/user/findid.css"%}">
{% endblock extrahead %}
{% block content%}
  <div class="container-mobile">
    <div class="mobile-header">
      <a href="{% url 'main:home' %}">
        <img src="{% static "logo/relanz-logo1.png" %}" alt="relanz-logo1">
      </a>
    </div>
    <form class="form-findid" action="{% url 'user:findid' %}" method="post">
      {% csrf_token %}
      <div class="title">
        <p class="title-text">아이디 찾기</p>
      </div>
      <div class="email-div">
        <p class="input-email-text">e-mail</p>
        <label class="email" for="email">e-mail</label>
        <input class="email-input" type="email" name="email" id="" placeholder="이메일을 입력해주세요">
      </div>
      <div class="info-message-div">
        <div class="info-message-div-div">
          {% if error %}
            <p class="error">{{ error }}</p>
            <a class="login-btn" href="{% url 'user:signin' %}">로그인</a>
          {% endif %}
          {% if success %}
            <div class="info-message-div">
              <p class="success">{{ success }}</p>
              <div class="mark-div">
                <img src="{% static "icons/exclamation_mark.svg" %}" alt=".">
              </div>
              <p class="success-2">만약 이메일을 받지 못하셨다면, 등록하신 이메일을 다시 확인하거나 스팸 메일함을 확인해주새요!</p>
              <div class="login-btn-div">
                <a class="login-btn" href="{% url 'user:signin' %}">로그인</a>
                <a class="findpw-btn" href="{% url 'user:password_reset' %}">비밀번호 찾기</a>
              </div>
            </div>
          {% endif %}
        </div>
      </div>
      <input class="submit-btn" type="submit" value="아이디 찾기">
    </form>
    <div class="just-for-space"></div>
  </div>
{% endblock %}

{% block scripts%}{% endblock scripts%}

relanz/templates/user/moreInfo.html
{% extends 'mobileBase.html' %}
{% load static %}

{% block mobile_title %}
  moreInfo
{% endblock mobile_title %}

{% block mobile_extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/moreInfo.css"%}">
{% endblock mobile_extrahead %}

{% block mobile_content %}
  <div class="button-container relative">
    <div class="block-screen" id="block_screen" data-depth="y"></div>
    <div class="warning-absolute" id="warning_absolute">
      <p class="signout-ment">로그아웃 하시겠습니까?</p>
      <div class="button-div">
        <button class="no-btn-signout" onclick="sayNo(this)">아니요</button>
        <a href="{% url 'user:signout' %}" class="yes-btn">네</a>
      </div>
    </div>
    <a class="each-button-a" href="" id="a_blue_1">
      <p class="text-p blue-color">멤버십 전환</p>
      <div class="img-div">
        <img src="{% static "icons/right_single_arrow.svg" %}" alt="." class="img-tag" id="blue-1">
      </div>
    </a>
    <a class="each-button-a" href="" id="a_blue_2">
      <p class="text-p blue-color">버전 정보</p>
      <div class="img-div">
        <img src="{% static "icons/right_single_arrow.svg" %}" alt="." class="img-tag" id="blue-2">
      </div>
    </a>
    <a class="each-button-a" id="a_blue_3" onclick="signout(this)">
      <p class="text-p blue-color">로그아웃</p>
      <div class="img-div">
        <img src="{% static "icons/right_single_arrow.svg" %}" alt="." class="img-tag" id="blue-3">
      </div>
    </a>
    <a class="each-button-a" href="{% url "user:user_delete" %}" id="a_red_1">
      <p class="text-p red-color">회원탈퇴</p>
      <div class="img-div">
        <img src="{% static "icons/right_single_arrow.svg" %}" alt="." class="img-tag-red" id="red-1">
      </div>
    </a>
  </div>
  {% endblock %}
  
  {% block mobile-scripts %}
  <script>
    const block_screen = document.getElementById("block_screen");
    const warning_absolute = document.getElementById("warning_absolute");

    function signout(obj) {
      block_screen.dataset.depth = "y"
      block_screen.style.zIndex = "5";
      warning_absolute.style.zIndex = "10";
    }

    function sayNo(obj) {
      block_screen.dataset.depth = "n"
      block_screen.style.zIndex = "-1";
      warning_absolute.style.zIndex = "-1";
    }

    const moreIcon = document.querySelector(".mobile-nav > ul > li > .more > img");
    moreIcon.src = "{% static 'icons/More_icon_filled.png'%}";
  </script>
{% endblock %}

relanz/templates/user/pw_reset.html
{% extends 'mobileBase.html' %}
{% load static %}
{% block title %}
  findPassword
{% endblock title %}
{% block extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/user/pw_reset.css"%}">
{% endblock extrahead %}
{% block content%}
  <div class="container-mobile">
    <div class="mobile-header">
      <a href="{% url 'main:home' %}">
        <img src="{% static "logo/relanz-logo1.png" %}" alt="relanz-logo1">
      </a>
    </div>
    <form class="form-findid" method="post">
      {% csrf_token %}
      <div class="title">
        <p class="title-text">비밀번호 찾기</p>
      </div>
      <div class="email-div">
        <p class="input-email-text">e-mail</p>
        <label class="email" for="email">e-mail</label>
        {{ form.email }}
        {% comment %} <input class="email-input" type="email" name="email" id="" placeholder="이메일을 입력해주세요"> {% endcomment %}
      </div>
      <div class="info-message-div">
        <div class="info-message-div-div">
          {% if error %}
            <p class="error">{{ error }}</p>
            <a class="login-btn" href="{% url 'user:signin' %}">로그인</a>
          {% endif %}
          {% if success %}
            <div class="info-message-div">
              <p class="success">{{ success }}</p>
              <div class="mark-div">
                <img src="{% static "icons/exclamation_mark.svg" %}" alt=".">
              </div>
              <p class="success-2">만약 이메일을 받지 못하셨다면, 등록하신 이메일을 다시 확인하거나 스팸 메일함을 확인해주새요!</p>
              <div class="login-btn-div">
                <a class="login-btn" href="{% url 'user:signin' %}">로그인</a>
                <a class="findpw-btn" href="{% url 'user:password_reset' %}">비밀번호 찾기</a>
              </div>
            </div>
          {% endif %}
        </div>
      </div>
      <input class="submit-btn" type="submit" value="비밀번호 찾기">
    </form>
    <div class="just-for-space"></div>
  </div>
{% endblock %}

{% block scripts%}
{% endblock scripts%}

relanz/templates/user/pw_reset_complete.html
{% extends 'mobileBase.html' %}
{% load static %}
{% block title %}
  findPassword_confirm
{% endblock title %}
{% block extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/user/pw_reset_complete.css"%}">
{% endblock extrahead %}
{% block content%}
  <div class="container-mobile">
    <div class="mobile-header">
      <a href="{% url 'main:home' %}">
        <img src="{% static "logo/relanz-logo1.png" %}" alt="relanz-logo1">
      </a>
    </div>

    <div class="title">
      <p class="title-text">비밀번호 재설정</p>
    </div>

    <div class="email-div">
        <div class="image-div">
            <img src="{% static "images/welcome-box.png" %}" alt=".">
        </div>
        <div class="text-div">
            <p>비밀번호가 재설정되었습니다</p>
            <p>이제 로그인하세요!</p>
        </div>
    </div>

    <a class="submit-btn" href="{% url 'user:signin' %}">로그인하기</a>

    <div class="just-for-space"></div>
  </div>
{% endblock %}

{% block scripts%}{% endblock scripts%}

relanz/templates/user/pw_reset_done.html
{% extends 'mobileBase.html' %}
{% load static %}
{% block title %}
  findPassword
{% endblock title %}
{% block extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/user/pw_reset_done.css"%}">
{% endblock extrahead %}
{% block content%}
  <div class="container-mobile">
    <div class="mobile-header">
      <a href="{% url 'main:home' %}">
        <img src="{% static "logo/relanz-logo1.png" %}" alt="relanz-logo1">
      </a>
    </div>

    <div class="title">
      <p class="title-text">비밀번호 찾기</p>
    </div>

    <div class="email-div">
      <div class="info-div">
        <p class="info-big">비밀번호 재설정 링크가 전송되었습니다</p>
        <p class="info-small">작성하신 이메일로 비밀번호 재설정 안내문을 전송하였습니다</p>
      </div>

      <div class="warning-div">
        <div class="mark-div">
          <img src="{% static "icons/exclamation_mark.svg" %}" alt=".">
        </div>
        <div class="warning-box">만약 이메일을 받지 못하셨다면, 등록하신 이메일을 다시 확인하거나 스팸 메일을 확인해주세요!</div>
      </div>
    </div>

    <input class="submit-btn" type="submit" value="비밀번호 찾는 중">

    <div class="just-for-space"></div>
  </div>
{% endblock %}

{% block scripts%}{% endblock scripts%}

relanz/templates/user/signin.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  SignIn
{% endblock title %}
{% block extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/signin.css"%}">
{% endblock extrahead %}
{% block content%}
  <div class="container-mobile">
    <div class="container-for-relative">
      {% if messages %}
        {% for message in messages %}
          <div class="warning-user" id="warning_user_div">
            <p class="warning-ment">사용자의
              {{message}}가 올바르지 않습니다.</p>
            <button type="button" class="warning-btn" id="warning_btn">확인</button>
          </div>
        {% endfor %}
      {% endif %}

      <div class="small-message_mobile">
        <p>챌린지 말고, 이젠 릴렌지 하자!</p>
      </div>
      <div class="logo-box_big">
        <img src="{% static "logo/relanz-logo1.png" %}" alt="relanz-logo">
      </div>
      <div class="login-center-mobile">
        <h4>Login</h4>
      </div>
      <div class="login-form-div-mobile">
        <form action="" method="post">
          {% csrf_token %}
          <input type="text" placeholder="아이디 입력" name="username" id="username" class="username-input">
          <!-- name tag 그대로 유지 안하면 서버에서 데이터 받을 때 인식 못해요! -->
          <input type="password" placeholder="비밀번호 입력" name="password" id="password" class="password-input" autocomplete='off'>
          <!-- name tag 그대로 유지 안하면 서버에서 데이터 받을 때 인식 못해요! -->
          <div class="find-id-password">
            <a href="{% url 'user:findid' %}" class="find-id">아이디 찾기</a>
            <span>|</span>
            <a href="{% url 'user:password_reset' %}" class="find-password">비밀번호 찾기</a>
          </div>
          <input type="submit" value="로그인하기" name='login' class="submit-input">
          <!--여기도 동일하게 name tag 유지 해주셔야 되여!-->
        </form>
      </div>
      <div class="ask-signup-div">
        <p>아직 회원이 아니신가요?</p>
        <a href="{% url 'user:signup' %}" class="ask-signup-a">회원가입</a>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts%}
  <script src={% static "js/signin.js"%}></script>
{% endblock scripts%}