relanz/challenge/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'challenge'

urlpatterns = [
    path('<int:challenge_id>/', views.challenge, name="challenge"),
    path('participate/<int:challenge_id>', views.participate, name="participate"),
]

relanz/community/urls.py
from django.urls import path
from .views import new, detail, edit, delete, communityHome, like
from .views import new, detail, edit, delete, communityHome, like, myArticles

app_name = 'community'

urlpatterns = [
    path('communityHome/<int:challenge_id>', communityHome, name='communityHome'),
    path('<int:challenge_id>/<int:article_id>', detail, name='detail'),
    path('<int:challenge_id>/new', new, name='new'),
    path('edit/<int:challenge_id>/<int:article_id>', edit, name='edit'),
    path('delete/<int:challenge_id>/<int:article_id>', delete, name='delete'),
    path('<int:article_id>/like/', like, name='like'),
    path('communityHome/<int:challenge_id>/myArticles', myArticles, name='myArticles')
]

relanz/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('community/', include('community.urls')),
    path('challenge/', include('challenge.urls')),
    path('', include('django.contrib.auth.urls')),
    # path('', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

relanz/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
    path('ranking/', views.ranking, name="ranking"),
]

relanz/challenge/models.py
from django.db import models

# Create your models here.
class Challenge(models.Model):
    class Meta:
        db_table="challenge"

    title = models.CharField(max_length=32, unique=True, blank=False)
    sub_effect = models.TextField(blank=False)
    effect = models.TextField(blank=False)
    recommand = models.TextField(blank=False)
    image = models.ImageField()

    def __str__(self) -> str:
        return self.title

class ChallengeTag(models.Model):
    class Meta:
        db_table="challengeTag"
        
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, unique=True)
    #기본 태그
    morning = models.BooleanField(default=False, verbose_name='아침')  # 아침
    afternoon = models.BooleanField(default=False, verbose_name='점심')  # 점심
    evening = models.BooleanField(default=False, verbose_name='저녁')  # 저녁
    inside = models.BooleanField(default=False, verbose_name='실내')  # 실내
    outside = models.BooleanField(default=False, verbose_name='실외')  # 실외
    solo = models.BooleanField(default=False, verbose_name='혼자')  # 혼자
    group = models.BooleanField(default=False, verbose_name='여럿이')  # 여럿이
    pay = models.BooleanField(default=False, verbose_name='유료')  # 유료
    free = models.BooleanField(default=False, verbose_name='무료')  # 무료
    static = models.BooleanField(default=False, verbose_name='정적인')  # 정적인
    dynamic = models.BooleanField(default=False, verbose_name='동적인')  # 동적인
    #릴렌지 태그
    relaxation = models.BooleanField(default=False, verbose_name='피로해소')  # 피로해소
    immunity = models.BooleanField(default=False, verbose_name='면역력 향상')  # 면역력 향상
    easy = models.BooleanField(default=False, verbose_name='누구나 쉽게')  # 누구나 쉽게
    sleep = models.BooleanField(default=False, verbose_name='수면 개선')  # 수면 개선
    circulation = models.BooleanField(default=False, verbose_name='혈액순환 촉진')  # 혈액순환 촉진
    muscle = models.BooleanField(default=False, verbose_name='근육이완')  # 근육이완
    stability = models.BooleanField(default=False, verbose_name='정서 안정')  # 정서 안정
    concentration = models.BooleanField(default=False, verbose_name='집중력 향상')  # 집중력 향상
    creativity = models.BooleanField(default=False, verbose_name='창의력 발휘')  # 창의력 발휘
    satisfaction = models.BooleanField(default=False, verbose_name='만족감 증진')  # 만족감 증진
    achievement = models.BooleanField(default=False, verbose_name='성취감')  # 성취감
    depression = models.BooleanField(default=False, verbose_name='우울감 개선')  # 우울감 개선
    selfesteem = models.BooleanField(default=False, verbose_name='자아존중감 형성')  # 자아존중감 형성
    organization = models.BooleanField(default=False, verbose_name='감정 정리')  # 감정 정리
    expression = models.BooleanField(default=False, verbose_name='표현력 향상')  # 표현력 향상
    precision = models.BooleanField(default=False, verbose_name='꼼꼼함 향상')  # 꼼꼼함 향상
    easylearn = models.BooleanField(default=False, verbose_name='배우기 쉬운')  # 배우기 쉬운
    dexterity = models.BooleanField(default=False, verbose_name='손재주 향상')  # 손재주 향상
    motor = models.BooleanField(default=False, verbose_name='미세 운동 능력 발달')  # 미세 운동 능력 발달
    memory = models.BooleanField(default=False, verbose_name='기억력 향상')  # 기억력 향상
    skeletal = models.BooleanField(default=False, verbose_name='근육과 골격 강화')  # 근육과 골격 강화
    balance = models.BooleanField(default=False, verbose_name='균형감각 향상')  # 균형감각 향상
    flexibility = models.BooleanField(default=False, verbose_name='유연성 향상')  # 유연성 향상
    sociability = models.BooleanField(default=False, verbose_name='사회성 향상')  # 사회성 향상
    cooperation = models.BooleanField(default=False, verbose_name='협동성 향상')  # 협동성 향상
    bloodpressure = models.BooleanField(default=False, verbose_name='혈압 낮춤')  # 혈압 낮춤
    problemsolving = models.BooleanField(default=False, verbose_name='문제 해결 능력 향상')  # 문제 해결 능력 향상
    innerpeace = models.BooleanField(default=False, verbose_name='마음 진정')  # 마음 진정
    positive = models.BooleanField(default=False, verbose_name='긍정적인 생각')  # 긍정적인 생각
    mood = models.BooleanField(default=False, verbose_name='기분 전환')  # 기분 전환
    anxiety = models.BooleanField(default=False, verbose_name='불안 해소')  # 불안 해소
    bedtime = models.BooleanField(default=False, verbose_name='취침 전')  # 취침 전
    socialrelationship = models.BooleanField(default=False, verbose_name='사회적 관계 개선')  # 사회적 관계 개선
    newchallenge = models.BooleanField(default=False, verbose_name='새로운 도전')  # 새로운 도전
    friends = models.BooleanField(default=False, verbose_name='친구와 함께')  # 친구와 함께
    awareness = models.BooleanField(default=False, verbose_name='도전 의식')  # 도전 의식
    confidence = models.BooleanField(default=False, verbose_name='자신감') # 자신감
    output = models.BooleanField(default=False, verbose_name='산출물') # 산출물


class Participant(models.Model):
    class Meta:
        db_table="participant" # 오타 수정: participaint -> participant

    user = models.ForeignKey('user.User', on_delete=models.CASCADE)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name='challenge')

relanz/challenge/views.py
from django.shortcuts import render, redirect
from user.models import User, UserTag
from challenge.models import Challenge, ChallengeTag, Participant
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict


@login_required
def challenge(request, challenge_id):
	user=request.user
	if user.nickname is None:
			return redirect('user:content')
	challenge = Challenge.objects.get(id=challenge_id)
	challenge_tag = ChallengeTag.objects.get(challenge_id=challenge_id)
	
	# 챌린지가 갖고 있는 기본 태그
	challenge_basic_tags = {
		'아침': challenge_tag.morning,
		'점심': challenge_tag.afternoon,
		'저녁': challenge_tag.evening,
		'실내': challenge_tag.inside,
		'실외': challenge_tag.outside,
		'혼자': challenge_tag.solo,
		'여럿이': challenge_tag.group,
		'유료': challenge_tag.pay,
		'무료': challenge_tag.free,
		'정적인': challenge_tag.static,
		'동적인': challenge_tag.dynamic,
		}
	
	challenge_tag_list=[]
	for tag_name, tag_value in challenge_basic_tags.items():
		if tag_value is True:
			challenge_tag_list.append(tag_name)
	participant_count = len(Participant.objects.filter(challenge=challenge_id))
	
	participated = Participant.objects.filter(user=user, challenge=challenge) # 이 챌린지 참여했는지 안했는지 체크 위해 변수 만듬

	res_data = {'challenge':challenge, 'challenge_tag':challenge_tag_list, 'participant':participant_count, 'participated':participated, 'challenge_tag_real':challenge_tag}
	return render(request, 'challenge/challenge.html', res_data)



@login_required
def participate(request, challenge_id):
	user = request.user
	if user.nickname is None:
		return redirect('user:content')
	if Participant.objects.filter(user=user.id, challenge=challenge_id):
		return redirect("challenge:challenge", challenge_id)
	

	challenge = Challenge.objects.get(id=challenge_id)
	challenge_tag = ChallengeTag.objects.get(challenge=challenge_id)
	challenge_tag_dict = model_to_dict(challenge_tag)

	# 기본 태그 dictionary
	challenge_basic_tags = {
		'morning': challenge_tag.morning,
		'afternoon': challenge_tag.afternoon,
		'evening': challenge_tag.evening,
		'inside': challenge_tag.inside,
		'outside': challenge_tag.outside,
		'solo': challenge_tag.solo,
		'group': challenge_tag.group,
		'pay': challenge_tag.pay,
		'free': challenge_tag.free,
		'static': challenge_tag.static,
		'dynamic': challenge_tag.dynamic,
		}
	
	# 기본 태그 list
	challenge_basic_list=[]
	for tag_name, tag_value in challenge_basic_tags.items():
		if tag_value is True:
			challenge_basic_list.append(tag_name)
			

	# 챌린지가 갖고 있는 태그 list
	challenge_tag_list=[]
	challenge_tag_dict = model_to_dict(challenge_tag)
	for tag_name, tag_value in challenge_tag_dict.items():
		if tag_value is True and tag_name not in challenge_basic_list:
			challenge_tag_list.append(tag_name)  

	# user가 갖고 있는 tag 정보 갖고오기
	user_tag = UserTag.objects.get(user=user.id)

	# 챌린지가 갖고 있는 tag명을 이용해서 user_tag를 파싱후 +1 해주기
	for tag_name in challenge_tag_list:
		setattr(user_tag, tag_name, getattr(user_tag, tag_name) + 1)
	user_tag.save()

	participant = Participant(user=user, challenge=challenge)
	participant.save()

	res_data = {"user": user.nickname, 'challenge':challenge, 'participant':participant}
	return render(request, 'challenge/participate.html', res_data)

relanz/templates/challenge/challenge.html
{% extends 'mobileBase.html' %}
{% load static %}
{% block mobile_title %}
  challenge
{% endblock mobile_title %}
{% block mobile_extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/challenge.css"%}">
{% endblock mobile_extrahead %}
{% block mobile_content%}
  <div class="scroll container-mobile">
    <div class="main-img-div">
            <img src="{% static challenge.image %}" alt="이미지">
    </div>
    <div class="main-container-div scroll">
        <div class="nav-div-absolute">
            <div class="nav-info">
                <a href="{% url 'challenge:challenge' challenge_id=challenge.id %}">릴렌지 안내</a>
            </div>
            <div class="nav-board">
                {% comment %} 여기에 커뮤게시판으로 가기 url {% endcomment %}
                <a href="{% url 'community:communityHome' challenge_id=challenge.id %}">커뮤니티 게시판</a>
            </div>
        </div>
        <div class="title-container-div">
            <div class="title-div">
                <div class="img-div">
                    <img src="{% static "icons/check_circle_down_lean.png" %}" alt=".">
                </div>
                <p class="title-p">{{challenge.title}}</p>
            </div>
            <div class="participant-count-div">
                <div class="participant-img-div">
                    <img src="{% static "icons/human_shaped.png" %}" alt=".">
                </div>
                <small class="participant-count-small">{{participant}}명이 참여 중인 릴렌지</small>
            </div>
        </div>
        <div class="tag-container-div">
            <div class="tag-div scroll">
                <div class="label">관련 태그</div>
                <ul class="scroll tag-list-ul">
                    {% for item in challenge_tag %}
                        <li class="tag-item-li">
                            {{item}}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="effect-div">
                <div class="label">효과</div>
                <div class="effect-text">{{challenge.sub_effect|linebreaksbr}}</div>
            </div>
        </div>
        <div class="content-container-div">
            <div class="effect-div">
                <div class="title">해소효과</div>
                <div class="content new-p" id="linebreaks_fix_1">{{challenge.effect|linebreaksbr}}</div>
            </div>
            <div class="recommand-to-people-container-div">
                <div class="title">이런 사람에게 추천해요!</div>
                <div class="content new-p" id="linebreaks_fix_2" >{{challenge.recommand|linebreaksbr}}</div>
            </div>
            {% comment %} 여기가 장소라 if 템플릿 사용하면 되용! {% endcomment %}
            <div class="recommand-place-container-outer-div">
                {% if challenge_tag_real.pay %}
                    <div class="recommand-place-container-div">
                        <div class="title-div">
                            <div class="img-div">
                                <img src="{% static "icons/map_point.png" %}" alt=".">
                            </div>
                            <p>추천 장소 안내</p>
                        </div>
                        <div class="text-info-div">
                            <p>유로 활동의 경우 릴렌즈에서 추천 장소를 안내해드려요!</p>
                        </div>
                        {% if challenge.id == 1 %}
                            <a href='https://map.naver.com/v5/search/%EB%B0%98%EC%8B%A0%EC%9A%95?c=15,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% elif challenge.id == 2 %}
                            <a href='https://map.naver.com/v5/search/%ED%85%9C%ED%94%8C%EC%8A%A4%ED%85%8C%EC%9D%B4?c=13,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% elif challenge.id == 3 %}
                            <a href='https://map.naver.com/v5/search/%EC%8B%AD%EC%9E%90%EC%88%98?c=13,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% elif challenge.id == 4 %}
                            <a href='https://map.naver.com/v5/search/%ED%8D%BC%EC%A6%90?c=15,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% elif challenge.id == 5 %}
                            <a href='https://map.naver.com/v5/search/%ED%95%84%EC%82%AC?c=15,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% elif challenge.id == 6 %}
                            <a href='https://map.naver.com/v5/search/%EB%9E%98%ED%94%84%ED%8C%85?c=13,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% elif challenge.id == 7 %}
                            <a href='https://map.naver.com/v5/search/%EB%9E%98%ED%94%84%ED%8C%85?c=13,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% elif challenge.id == 8 %}
                            <a href='https://map.naver.com/v5/search/%EC%9E%90%EC%A0%84%EA%B1%B0?c=13,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% elif challenge.id == 9 %}
                            <a href='https://map.naver.com/v5/search/%EC%9D%B8%EC%84%BC%EC%8A%A4%20%ED%85%8C%EB%9D%BC%ED%94%BC?c=15,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% elif challenge.id == 10 %}
                            <a href='https://map.naver.com/v5/search/%EC%84%9C%ED%95%91?c=13,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% elif challenge.id == 11 %}
                            <a href='https://map.naver.com/v5/search/%ED%8C%8C%EC%BF%A0%EB%A5%B4?c=13,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% elif challenge.id == 12 %}
                            <a href='https://map.naver.com/v5/search/%EC%82%AC%EC%9A%B4%EB%93%9C%20%ED%85%8C%EB%9D%BC%ED%94%BC?c=15,0,0,0,dh' class="go-to-place-a">
                                <div>장소 보러 가기</div>
                            </a>
                        {% endif %}
                        
                    </div>
                {% endif %}
            </div>
            <div class="start-btn-div">
                {% comment %} 이미 참여한 경우 시작하기 버튼이 아닌 게시판 구경하기 버튼으로 바뀝니당! {% endcomment %}
                {% if participated %}
                    <a href="{% url 'community:communityHome' challenge.id %}">게시판 구경하기</a>
                {% else %}
                    <a href="{% url 'challenge:participate' challenge_id=challenge.id %}">시작하기</a>
                {% endif %}
            </div>
        </div>
    </div>

  </div>
{% endblock %}

{% block mobile-scripts%}
  <script src={% static "js/challenge.js"%}></script>
{% endblock %}

relanz/templates/challenge/participate.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  findId
{% endblock title %}
{% block extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/participate.css"%}">
{% endblock extrahead %}
{% block content%}
  <div class="container-mobile">
    <div class="title">
      <p>{{user}}님의 릴렌지 활동이</p>
      <p>시작되었습니다!</p>
    </div>
    <div class="image-box">
      <img src="{% static "images/welcome-box.png" %}" alt=".">
    </div>
    <div class="info-middle-div">
      <p>오늘부터
        {{user}}님을 위한</p>
      <p>스트레스 해소 시간을 가져보아요!</p>
    </div>
    <div class="button-div">
      <a href="{% url 'community:communityHome' challenge.id %}">커뮤니티 구경하기</a>
    </div>
  </div>
{% endblock %}

{% block scripts%}
  <script src={% static "js/participate.js"%}></script>
{% endblock scripts%}