relanz/challenge/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'challenge'

urlpatterns = [
    path('<int:challenge_id>/', views.challenge, name="challenge"),
    path('participate/<int:challenge_id>', views.participate, name="participate"),
]

relanz/community/urls.py
from django.urls import path
from .views import new, detail, edit, delete, communityHome, like
from .views import new, detail, edit, delete, communityHome, like, myArticles

app_name = 'community'

urlpatterns = [
    path('communityHome/<int:challenge_id>', communityHome, name='communityHome'),
    path('<int:challenge_id>/<int:article_id>', detail, name='detail'),
    path('<int:challenge_id>/new', new, name='new'),
    path('edit/<int:challenge_id>/<int:article_id>', edit, name='edit'),
    path('delete/<int:challenge_id>/<int:article_id>', delete, name='delete'),
    path('<int:article_id>/like/', like, name='like'),
    path('communityHome/<int:challenge_id>/myArticles', myArticles, name='myArticles')
]

relanz/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user.urls')),
    path('community/', include('community.urls')),
    path('challenge/', include('challenge.urls')),
    path('', include('django.contrib.auth.urls')),
    # path('', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

relanz/main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name="home"),
    path('ranking/', views.ranking, name="ranking"),
]

relanz/community/models.py
from django.db import models
from user.models import User
from challenge.models import Participant, Challenge

# Create your models here.

class Article(models.Model):
    challenge = models.ForeignKey(Challenge, default=1, on_delete=models.CASCADE)
    author = models.ForeignKey(Participant, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(blank=True, null=True, upload_to='')
    article_score = models.IntegerField(default=0)

class Like(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True)
    likedUser = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

relanz/community/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = [
            'image',
        ]

    def clean(self):
        cleaned_data = super().clean()
        image = cleaned_data.get('image')
        if not image:
            raise forms.ValidationError('사진 파일이 필요합니다.')

relanz/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ArticleForm
from .models import Article, Like, Participant
from user.models import User
from challenge.models import Challenge
from django.contrib.auth.decorators import login_required
from config.email_decorator import email_verified_required
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.utils import timezone
from datetime import timedelta
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

import re, json

# Create your views here.
@csrf_exempt
@login_required(login_url='/user/signin')
@email_verified_required
def communityHome(request, challenge_id):
    user = request.user
    if request.method == 'GET':
        challenge = Challenge.objects.get(id=challenge_id)
         # a 챌린지의 게시물들만 가져오기
        articles = Article.objects.filter(challenge=challenge).order_by('-created_at')
         # 이 챌린지 참여했는지 안했는지 체크 위해 변수 만듬
        participated = Participant.objects.filter(user=user, challenge=challenge) 
        participants = len(Participant.objects.filter(challenge=challenge))
        # 한페이지 당 사진 9개로 설정
        paginator = Paginator(articles, 9) 
        try:
            page_number = request.GET.get('page')
            if page_number is not None and paginator.num_pages < int(page_number):
                message = {'message': '더 이상 기록이 없습니다.'}
                return JsonResponse(message, status=400)
            elif page_number is not None:
                page_obj = paginator.get_page(page_number)
                serialized_data = serializers.serialize('json', page_obj.object_list)
                return JsonResponse(serialized_data, safe=False, status=200)
            else:
                page_obj = paginator.get_page(page_number)

        except PageNotAnInteger:
            page = 1
            page_obj = paginator.get_page(page)

        except EmptyPage:
            page=paginator.num_pages
            page_obj=paginator.page(page)
            
        res_data = {'articles': articles, 'challenge':challenge, 'participated':participated, 'participants':participants,'articles':page_obj}

        return render(request, 'community/communityHome.html', res_data)
    if request.method == 'POST':
        user = request.user
        articles = Article.objects.filter(author__user = user, challenge=challenge_id)
        if articles.exists():
            current_time = timezone.now()
            articles = articles.order_by('-created_at')
            last_article = articles[0]
            time_difference = current_time - last_article.created_at
            if time_difference < timedelta(days=1):
                message = {'message': '릴렌지 기록은 하루에 한 번만 가능합니다.'}
                # return JsonResponse(message, status=400)
                messages.add_message(request, messages.ERROR, '릴렌지 기록은 하루에 한 번만 가능합니다')
                return redirect('community:communityHome', challenge_id)
            else:
                return redirect('community:new', challenge_id)
        else:
            return redirect('community:new', challenge_id)

@csrf_exempt
@login_required(login_url='/user/signin')
@email_verified_required
def new(request, challenge_id):
    challenge = Challenge.objects.get(id=challenge_id)
    try:
        participant = Participant.objects.get(user=request.user, challenge=challenge)
    
    # 챌린지에 참여하지 않았는데, 글을 작성하려고 할 때
    except Participant.DoesNotExist:
        return redirect('community:communityHome', challenge_id)
    form = ArticleForm()

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)

        if form.is_valid():
            article = form.save(commit=False)
            article.author = participant
            article.challenge = challenge
            article.user = request.user
            duplication_article = Article.objects.filter(author=participant, challenge=challenge)
            if duplication_article.exists():
                article.article_score = 100
            else:
                article.article_score = 500
            article.save()
            user=User.objects.get(id=request.user.id)
            user.score += article.article_score
            user.save()

        else:
            message = {'message': '사진 파일이 없습니다.'}
            return JsonResponse(message, status=400)
        messages.add_message(request, messages.SUCCESS, f'{article.article_score}')
        return redirect('community:detail', challenge.id, article.id)
    
    res_data = {'form':form, 'challenge':challenge}
    return render(request, 'community/new.html', res_data)


@login_required(login_url='/user/signin')
@email_verified_required
def detail(request, challenge_id, article_id):
    challenge = Challenge.objects.get(id=challenge_id)
    article = get_object_or_404(Article, pk=article_id)
    articles = Article.objects.filter(challenge=challenge).order_by('-created_at')
    participant = Participant.objects.filter(challenge_id=challenge_id)
    
    paginator = Paginator(articles, 1)
    for article_ in articles:
        for i in range(1, paginator.num_pages+1):
            if paginator.get_page(i)[0].id == article_.id:
                article_num = i
    try:     
        page_number = request.GET.get('page')
        print(page_number)
        if page_number is not None and paginator.num_pages < int(page_number):
                message = {'message': '더 이상 기록이 없습니다.'}
                return JsonResponse(message, status=400)
        else:
            page_obj = paginator.get_page(page_number)
            like_count = len(Like.objects.filter(article=page_obj.object_list[0]))
            author_nickname = page_obj.object_list[0].author.user.nickname
            isExist = Like.objects.filter(likedUser=request.user, article=page_obj.object_list[0]).exists() 
    
    except PageNotAnInteger:
        page_number = 1
        page_obj = paginator.get_page(page_number)
        like_count = len(Like.objects.filter(article=article))
        author_nickname = article.author.user.nickname
        isExist = Like.objects.filter(likedUser=request.user, article=article).exists()
    
    except EmptyPage:
        page=paginator.num_pages
        page_obj=paginator.page(page)
        messages.add_message(request, messages.ERROR, '더 이상 인증 글이 없습니다.')
    
    res_data = {'challenge':challenge, 'articles':page_obj, 'like_count':like_count, 'author_nickname':author_nickname, "isExist": isExist, "participant":participant, "current": article}
    return render(request, 'community/detail.html', res_data)

@csrf_exempt
@login_required(login_url='/user/signin')
@email_verified_required
def edit(request, challenge_id, article_id):
    challenge = Challenge.objects.get(id=challenge_id)
    article = get_object_or_404(Article, pk=article_id)

    form = ArticleForm(instance=article)

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)

        if form.is_valid():
            article = form.save()
            return redirect('community:detail', challenge.id, article.id)
    
    res_data = {'form':form, 'challenge':challenge, 'article':article}
    return render(request, 'community/edit.html', res_data)

@login_required(login_url='/user/signin')
@email_verified_required
def delete(request, challenge_id, article_id):
    article = get_object_or_404(Article, pk=article_id)

    article.delete()

    return redirect('main:home')

@login_required(login_url='/user/signin')
@email_verified_required
def like(request, article_id):   
    article = get_object_or_404(Article, pk=article_id)

    referer = request.META.get('HTTP_REFERER')
    
    # 이미 좋아요 누른 경우 detail로 이동, 본인 글에 좋아요 누르기 가능
    isExist = Like.objects.filter(likedUser=request.user, article=article).exists()
    if isExist:
        try:
            get_object_or_404(Like, Q(article=article_id) & Q(likedUser=request.user.id)).delete()
        except:
            like_count = len(Like.objects.filter(article=article))
            likeCount = {
                    'likeCount': like_count,
                    "isClicked": isExist
            }
            messages.add_message(request, messages.ERROR, '다시 시도해주세요')
            return JsonResponse(likeCount, status=400)

        like_count = len(Like.objects.filter(article=article))
        likeCount = {
            'likeCount': like_count,
            "isClicked": isExist
        }
        # detail 페이지에서 좋아요를 시도할 때
        if referer:
            pattern = r'community/\d+/\d+'
            match = re.search(pattern, referer)
            if match:
                return JsonResponse(likeCount, status=200)
            
        return redirect("community:detail", challenge_id=article.challenge.id, article_id=article.id)

    # 좋아요 아직 안 누른 경우 Like 객체 만들기
    else:
        try:
            like = Like()
            like.article = get_object_or_404(Article, pk=article_id)
            like.likedUser = request.user
            like.save()
        except:
            messages.add_message(request, messages.ERROR, '다시 시도해주세요')
            like_count = len(Like.objects.filter(article=article))
            likeCount = {
                    'likeCount': like_count,
                    "isClicked": isExist
            }
            return JsonResponse(likeCount, status=400)

        like_count = len(Like.objects.filter(article=article))
        likeCount = {
                'likeCount': like_count,
                "isClicked": isExist
        }

        if referer:
            pattern = r'community/\d+/\d+'
            match = re.search(pattern, referer)
            if match:
                return JsonResponse(likeCount, status=200)
        return redirect('community:detail', challenge_id=article.challenge.id, article_id=article.id)


@login_required(login_url='/user/signin')

relanz/templates/community/communityHome.html
{% extends 'mobileBase.html' %}
{% load static %}
{% block mobile_title %}
    communityHome
{% endblock mobile_title %}
{% block mobile_extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/communityHome.css"%}">
{% endblock mobile_extrahead %}
{% block mobile_content%}
    <div class="container-mobile">
        <div class="main-img-div">
            {% if challenge.image %}
                <img src="{% static challenge.image %}" alt="이미지">
            {% else %}
                <img src="{% static "images/leein_example.jpeg" %}" alt=".">
            {% endif %}
        </div>
        <div class="main-container-div">
            <div class="nav-div-absolute">
                <div class="nav-info">
                    <a href="{% url 'challenge:challenge' challenge_id=challenge.id %}">릴렌지 안내</a>
                </div>
                <div class="nav-board">
                    <a href="{% url 'community:communityHome' challenge_id=challenge.id %}">커뮤니티 게시판</a>
                </div>
            </div>
        </div>
        <div class="title-container-div">
            <div class="title-div">
                <div class="img-div">
                    <img src="{% static "icons/check_circle_down_lean.png" %}" alt=".">
                </div>
                {% if challenge.title %}
                    <p class="title-p">{{challenge.title}}</p>
                {% else %}
                    <p class="title-p">변수명으로 이름 넘겨줘잉~</p>
                {% endif %}
            </div>
            <div class="participant-count-div">
                <div class="participant-img-div">
                    <img src="{% static "icons/human_shaped.png" %}" alt=".">
                </div>
                {% if participants %}
                    <small class="participant-count-small">{{participants}} 명이 참여 중인 릴렌지</small>
                {% else %}
                <small class="participant-count-small">00 명이 참여 중인 릴렌지</small>
                {% endif %}
            </div>
        </div>
        <div class="tag-record-div">
            {% if participated %}
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="record-btn">내 기록 남기기</button>
                </form>
                
                {% comment %} 유저 아이디랑 챌린지 아이디 활용해서 걸러야함! {% endcomment %}
                <a href="{% url 'community:myArticles' challenge.id %}" class="record-btn">내 기록 모아보기</a>

            {% else %}
                <a href="{% url 'challenge:participate' challenge.id %}" class="record-btn">시작하기</a>
            {% endif %}

            {% if messages %}
                {% for message in messages %}
                    <div class="warning-user" id="warning_user_div">
                        <p class="warning-ment">{{message}}</p>
                        <button type="button" class="warning-btn" id="warning_btn" onclick="clickCheckBtn()">확인</button>
                    </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="images-box-div" id="images_box_div" data-startnum="2" data-askurl="{% url "community:communityHome" challenge.id %}">
            {% comment %} 여기에 이미지 url이 list로 던저져야함! -> 했습니당 {% endcomment %}
                {% comment %} reversed 사용해서 가장 최신에 올린 게시물이 위에 있도록 설정 {% endcomment %}
            {% for article in articles %}
                <a href="{% url 'community:detail' challenge.id article.id %}" class="images-box-single-a">
                    <div class="images-box-single">
                        {% if article.image %}
                            <img src="{{article.image.url}}"" alt=".">
                        {% endif %}
                    </div>
                </a>
            {% endfor %}
            
        </div>
        <div class="loading-div">
            <div class="loading-img-div" id="loading_img_div">
                <img src="{% static "icons/loading.png" %}" alt=".">
            </div>
        </div>
        <div class="just-for-margin-div" id="div_end"></div>
        <div class="see-full-go-next" id="see_full_go_next"></div>
    </div>
{% endblock %}
   
{% block mobile-scripts%}
    <script src={% static "js/communityHome.js"%}></script>
    <script>
        function clickCheckBtn() {
            document.querySelector(".warning-user").classList.add("hide");
        } 
    </script>
{% endblock %}

relanz/templates/community/detail.html
{% extends 'mobileBase.html' %}
{% load static %}
{% block mobile_title %}
    detail
{% endblock mobile_title %}
{% block mobile_extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/detail.css"%}">
{% endblock mobile_extrahead %}
{% block mobile_content%}
    <div class="container-mobile">
        <div class="main-img-div">
            {% if challenge.image %}
                <img src="{% static challenge.image %}" alt="이미지">
            {% else %}
                <img src="{% static "images/leein_example.jpeg" %}" alt=".">
            {% endif %}
        </div>
        <div class="main-container-div">
            <div class="nav-div-absolute">
                <div class="nav-info">
                    <a href="{% url 'challenge:challenge' challenge.id %}">릴렌지 안내</a>
                </div>
                <div class="nav-board">
                    <a href="{% url 'community:communityHome' challenge.id %}">커뮤니티 게시판</a>
                </div>
            </div>
        </div>
        <div class="title-container-div">
            <div class="title-div">
                <div class="img-div">
                    <img src="{% static "icons/check_circle_down_lean.png" %}" alt=".">
                </div>
                {% if challenge.title %}
                    <p class="title-p">{{challenge.title}}</p>
                {% else %}
                    <p class="title-p">변수명으로 이름 넘겨줘잉~</p>
                {% endif %}
            </div>
            <div class="participant-count-div">
                <div class="participant-img-div">
                    <img src="{% static "icons/human_shaped.png" %}" alt=".">
                </div>
                {% if participant %}
                    <small class="participant-count-small">{{participant|length}} 명이 참여 중인 릴렌지</small>
                {% else %}
                <small class="participant-count-small">0 명이 참여 중인 릴렌지</small>
                {% endif %}
            </div>
        </div>
        <div class="detail-content-background">
            
            
            <div class="main-content-div">
            {% for article in articles %}
                <div class="header-div">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert-msg-div" id="alert_user_div" onclick="clickCancelBtn(this)">
                                <p class="score-ment">오늘의 기록을 남긴 멋진 당신,<br>스코어를 획득하셨습니다!</p>
                                <div class="score-box">
                                    {% if message|floatformat == "500" %}
                                        <span class="first">1st</span>
                                    {% endif %}
                                    <img src="{% static 'icons/rStar.png' %}" alt="star">
                                    <span class="plus">+</span>
                                    <span class="score">{{message}}</span>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}
                    
                    <div class="user-info-div">
                        <div class="profile-wrapper">
                            <div class="profile-circle">
                              <div class="back-hair"></div>
                              <div class="face"></div>
                              <div class="front-hair"></div>
                              <div class="eyebrows"></div>
                              <div class="eyes"></div>
                              <div class="nose"></div>
                              <div class="mouth"></div>
                              <div class="makeup"></div>
                              <div class="clothes"></div>
                              <div class="acc"></div>
                            </div>
                          </div>
                        <div class="nickname-created-div">
                            <div class="user-nickname">{{author_nickname}} 님</div>
                            <div class="content-created-at">{{current.created_at}}</div>
                        </div>
                    </div>
                    <div class="like-dislike-div">
                        <span class="like-count" id="like_count">{{like_count}}</span>
                        <div id="like_count_image_div" data-url="{% url 'community:like' current.id %}" onclick="clickLikeHeartBtn(this)">
                            <div class="like-img-div">
                                {% if isExist %}
                                    <div class="like-heart-img-div", id="like_heart_img_div">
                                        <img class="like-heart-img" src="{% static "icons/fill_heart.svg" %}" alt=".">
                                    </div>
                                    <div class="dislike-heart-img-div hide" id="dislike_heart_img_div">
                                        <img class="dislike-heart-img" src="{% static "icons/unfill_heart.png" %}" alt=".">
                                    </div>
                                {% else %}
                                    <div class="like-heart-img-div hide", id="like_heart_img_div">
                                        <img class="like-heart-img" src="{% static "icons/fill_heart.svg" %}" alt=".">
                                    </div>
                                    <div class="dislike-heart-img-div" id="dislike_heart_img_div">
                                        <img class="dislike-heart-img" src="{% static "icons/unfill_heart.png" %}" alt=".">
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="main-image-div">
                    {% if current.image %}
                        <img src="{{current.image.url}}" alt="이미지">
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="rest-image-bundle-div" id="focus">
        </div>
    </div>
{% endblock %}
   
{% block mobile-scripts%}
    <script src={% static "js/detail.js"%}></script>
    <script>
        function renderProfileCombination(combinationData) {
            const backHairElement = document.querySelector(".back-hair");
            const frontHairElement = document.querySelector(".front-hair");
            const eyebrowsElement = document.querySelector(".eyebrows");
            const eyesElement = document.querySelector(".eyes");
            const noseElement = document.querySelector(".nose");
            const mouthElement = document.querySelector(".mouth");
            const cheekElement = document.querySelector(".makeup");
            const faceElement = document.querySelector(".face");
            const clothesElement = document.querySelector(".clothes");
            const accElement = document.querySelector(".acc");
          
            // 각 조합 요소의 숫자에 해당하는 이미지 경로 설정
            frontHairElement.style.backgroundImage = `url("{% static 'character/fronthair/fronthair' %}${combinationData[0]}.png")`;
            if (combinationData[1] > 0)
              backHairElement.style.backgroundImage = `url("{% static 'character/backhair/backhair' %}${combinationData[1]}.png")`;
            eyebrowsElement.style.backgroundImage = `url("{% static 'character/brows/brows' %}${combinationData[2]}.png")`;
            eyesElement.style.backgroundImage = `url("{% static 'character/eyes/eyes' %}${combinationData[3]}.png")`;
            noseElement.style.backgroundImage = `url("{% static 'character/nose/nose' %}${combinationData[4]}.png")`;
            mouthElement.style.backgroundImage = `url("{% static 'character/mouth/mouth' %}${combinationData[5]}.png")`;
            if (combinationData[6] > 0)
              cheekElement.style.backgroundImage = `url("{% static 'character/makeup/makeup' %}${combinationData[6]}.png")`;
            faceElement.style.backgroundImage = `url("{% static 'character/face.png' %}")`;
            clothesElement.style.backgroundImage = `url("{% static 'character/clothes/clothes' %}${combinationData[7]}.png")`;
            if (combinationData[8] > 0)
              accElement.style.backgroundImage = `url("{% static 'character/acc/acc' %}${combinationData[8]}.png")`;
        }
        renderProfileCombination("{{user.avatar}}");
    </script>
{% endblock %}

relanz/templates/community/edit.html
{% comment %} {% block extrahead %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock extrahead %} {% endcomment %}

{% block title %}
<h1>사진 수정 페이지</h1>
{% endblock title %}

{% block content %}
<form method="POST" action="{% url 'community:edit' challenge.id article.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="image" value="{{article.image}}"/>
    <input type="submit" value="수정하기">
</form>

<a href="{% url 'main:home' %}">홈</a>
<a href="{% url 'community:delete' challenge.id article.id %}">삭제하기</a>
{% endblock content %}

relanz/templates/community/myArticles.html
{% extends 'mobileBase.html' %}
{% load static %}
{% block mobile_title %}
  myArticles
{% endblock mobile_title %}
{% block mobile_extrahead %}
  <link rel="stylesheet" type="text/css" href="{% static "css/myArticles.css"%}">
{% endblock mobile_extrahead %}
{% block mobile_content%}
  <div class="container-mobile">
    <div class="main-img-div">
      {% if challenge.image %}
        <img src="{% static challenge.image %}" alt="이미지">
      {% else %}
        <img src="{% static "images/leein_example.jpeg" %}" alt=".">
      {% endif %}
    </div>
    <div class="main-container-div">
      <div class="nav-div-absolute">
        <div class="nav-info">
          <a href="{% url 'challenge:challenge' challenge_id=challenge.id %}">릴렌지 안내</a>
        </div>
        <div class="nav-board">
          <a href="{% url 'community:communityHome' challenge_id=challenge.id %}">커뮤니티 게시판</a>
        </div>
      </div>
    </div>
    <div class="title-container-div">
      <div class="title-div">
        <div class="img-div">
          <img src="{% static "icons/check_circle_down_lean.png" %}" alt=".">
        </div>
        {% if challenge.title %}
          <p class="title-p">{{challenge.title}}</p>
        {% else %}
          <p class="title-p">변수명으로 이름 넘겨줘잉~</p>
        {% endif %}
      </div>
      <div class="participant-count-div">
        <div class="participant-img-div">
          <img src="{% static "icons/human_shaped.png" %}" alt=".">
        </div>
        {% if participant %}
          <small class="participant-count-small">{{participant_count}}
            명이 참여 중인 릴렌지</small>
        {% else %}
          <small class="participant-count-small">00 명이 참여 중인 릴렌지</small>
        {% endif %}
      </div>
    </div>
    <div class="tag-record-div">
      {% if participant %}
        <a class="record-btn-2">나의 기록</a>
        <form action="{% url "community:communityHome" challenge.id %}" method="post">
          {% csrf_token %}
          <button class="record-btn" type="submit">내 기록 남기기</button>
        </form>
        {% comment %} <a href="{% url 'community:communityHome' challenge.id %}" class="record-btn">내 기록 남기기</a> {% endcomment %}

      {% else %}
        <a href="{% url 'challenge:participate' challenge.id %}" class="record-btn">시작하기</a>
      {% endif %}
    </div>
    <div class="images-box-div" id="images_box_div">
      {% for mediaUrl, article in zips reversed %}
        <a href="{% url 'community:detail' challenge.id article.id %}" class="images-box-single-a">
          <div class="images-box-single">
            <img src="{{mediaUrl}}" alt=".">
          </div>
        </a>
      {% endfor %}
    </div>
    <div class="loading-div">
      <div class="loading-img-div" id="loading_img_div">
        <img src="{% static "icons/loading.png" %}" alt=".">
      </div>
    </div>
    <div class="just-for-margin-div" id="div_end"></div>
    <div class="see-full-go-next" id="see_full_go_next"></div>
  </div>
{% endblock %}
  
{% block mobile-scripts%}
  <script src={% static "js/communityHome.js"%}></script>
{% endblock %}